source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'LPDemoProjectColletion' do

#数据库
pod 'FMDB'

##下拉刷新
#pod 'MJRefresh'

#图片加载
pod 'SDWebImage'

#网络请求
pod 'AFNetworking'


end
